### ISSUE TITLE
Aborting request

### ISSUE THREAD

**Issue by Mordred** [willhuang85/skipper-gridfs#20]
When upload is aborted I get this error:

```js
TypeError: object is not a function
    at onwriteError (_stream_writable.js:313:5)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at Writable.<anonymous> (/app/node_modules/skipper-gridfs/index.js:227:21)
    at Writable.g (events.js:199:16)
    at Writable.emit (events.js:129:20)
    at PassThrough.<anonymous> (/app/node_modules/skipper-gridfs/index.js:246:36)
    at PassThrough.g (events.js:199:16)
    at PassThrough.emit (events.js:129:20)
    at /app/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:65:17
    at Function.forEach (/app/node_modules/skipper/node_modules/lodash/dist/lodash.js:3298:15)
    at lodash.ctor.(anonymous function) [as each] (/app/node_modules/skipper/node_modules/lodash/dist/lodash.js:5925:31)
    at Upstream.fatalIncomingError (/app/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:55:18)
    at /app/node_modules/skipper/lib/Parser/prototype.parseReq.js:51:10
    at Function.forEach (/app/node_modules/skipper/node_modules/lodash/dist/lodash.js:3298:15)
    at lodash.ctor.(anonymous function) [as each] (/app/node_modules/skipper/node_modules/lodash/dist/lodash.js:5925:31)
    at Form.<anonymous> (/app/node_modules/skipper/lib/Parser/prototype.parseReq.js:50:23)
    at Form.emit (events.js:129:20)
    at handleError (/app/node_modules/skipper/node_modules/multiparty/index.js:196:12)
    at IncomingMessage.onReqAborted (/app/node_modules/skipper/node_modules/multiparty/index.js:175:5)
    at IncomingMessage.emit (events.js:104:17)
    at abortIncoming (_http_server.js:279:11)
    at Socket.socketOnEnd (_http_server.js:393:7)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11) [TypeError: object is not a function]
```

I am running #master branch

**Comment by penciltim** [comment]
I have the same problem, could some one help?????

**Comment by marclr** [comment]
+1, any solution or workaround?

**Comment by willhuang85** [comment]
I'll be working on it this weekend and see if I can resolve it. Can you give me some steps so I can reproduce it?  Or even better, write a test and submit a pull request

**Comment by japel** [comment]
Are you guys behind some kind of proxy like nginx or something? If so, I was able to get rid of this error by adding:
keepalive 16;
to the upstream definition... but this is probably just a workaround

**Comment by cburatto** [comment]
Hi. This is related to this skipper issue:

https://github.com/balderdashy/skipper/issues/49#issuecomment-196421841

That's the last error thrown -- which you can catch if using `domain`. It seems the adapter keeps throwing a couple of errors after the `.upload` function's life cycle. I don't know if this is an issue on this adapter or on the skipper behavior.

**Comment by cburatto** [comment]
I just created a pull request that might fix this
https://github.com/willhuang85/skipper-gridfs/pull/26
This error seems to be caused by the callback being called after an error was already emitted. Not sure if my solution is the best, but...
