### ISSUE TITLE
doesn't support connection URI for several hosts

### ISSUE THREAD

**Issue by arndtjenssen** [willhuang85/skipper-gridfs#25]
`mongodb://server1:27017/test.fs`
works well, but
`mongodb://server1:27017,server2:27017,server3:27017/test.fs`
or
`mongodb://server1:27017,server2:27017,server3:27017/test.fs?replicaSet=repl1`
throws an exception:

```
App 12400 stderr: /home/sever/repos/server/node_modules/skipper-gridfs/node_modules/mongodb/lib/mongodb/mongo_client.js:409
App 12400 stderr:           throw err
App 12400 stderr:                 ^
App 12400 stderr: TypeError: Cannot read property 'collection' of null
App 12400 stderr:     at Function.GridStore.exist (/home/server/repos/server/node_modules/skipper-gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:1012:5)
App 12400 stderr:     at /home/server/repos/server/node_modules/skipper-gridfs/index.js:68:27
App 12400 stderr:     at /home/server/repos/server/node_modules/skipper-gridfs/node_modules/mongodb/lib/mongodb/mongo_client.js:406:11
```

The bucket definition should be not part of the URI anyway..

**Comment by 1nstinct** [comment]
I am agree with @arndtjenssen . Because of this it is impossible to use replicaSet.
