### ISSUE TITLE
MongoError: Can't get executor for query { files_id: ObjectId('5863503bb05b55f81abea9b0'), n: { $gte: 0 } }

### ISSUE THREAD

**Issue by YAOHAO9** [willhuang85/skipper-gridfs#30]
{ MongoError: Can't get executor for query { files_id: ObjectId('5863503bb05b55f81abea9b0'), n: { $gte: 0 } }
    at Object.toError (e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\utils.js:114:11)
    at e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\db.js:1196:31
    at e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\db.js:1905:9
 at Server.Base._callHandler (e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\connection\base.js:453:41)
    at e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\connection\server.js:488:18
    at MongoReply.parseBody (e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
    at .<anonymous> (e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\connection\server.js:446:20)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:207:13)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.exports.Connection.createDataHandler (e:\NodeWorkspace\Sails-Vue\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\connection\connection.js:440:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'MongoError',
  ok: 0,
  errmsg: 'Can\'t get executor for query { files_id: ObjectId(\'5863503bb05b55f81abea9b0\'), n: { $gte: 0 } }',
  code: 17241,
  codeName: 'Location17241' }

**Comment by markus138** [comment]
not sure if this helps, but I got the same issue last week. for me it was a misconfiguration on my part (wrong mongo uri)

**Comment by sanjaygovindan** [comment]
@markus138  - What was misconfigured?

Running a pretty standard URI: mongodb://192.168.99.100:27017/dev.bucket

And getting the same issue as above

**Comment by sanjaygovindan** [comment]
Got it - Create a compound index on file_id and n. 
Error seems to be gone

Taken from here: [](http://stackoverflow.com/questions/30240883/mongodb-cant-get-query-executor-when-executing-geonear-aggregate )

**Comment by frostme** [comment]
Agree with @sanjaygovindan, I found this to be a GridFS issue of some lost indexes. 

running command 
`
db.fs.chunks.ensureIndex({ files_id : 1, n : 1 })
`
in mongo (where `fs` is your bucket name), fixes the issue.
