### ISSUE TITLE
file download error

### ISSUE THREAD

**Issue by heoyongun** [willhuang85/skipper-gridfs#35]
sailsjs  v1.0.1 

file download error

upload code like this

```
      req.file('background').upload({
        maxBytes: 10000000,
        adapter: require('skipper-gridfs'),
        uri: 'mongodb://localhost:27017/payment_db',
      }, async function (err, uploadedFiles) {
        if (err) return res.serverError(err);
        if (uploadedFiles.length === 0) {
          return res.badRequest('No file was uploaded');
        }

        const user = await User.findOne({
          email
        });

        let file = await FileManager.findOne({
          user: user.id
        });

        if (!file) {
          file = await FileManager.create({
            background: uploadedFiles[0],
            user: user.id
          }).fetch();
        } else {
          file = await FileManager.update({
            user: user.id
          },{
            background: uploadedFiles[0],
          }).fetch();
        }

        return res.ok({
          file
        });
      });
```
file upload it works good.

but download error.

some body help me.

dowload code like this 
```
// https://stackoverflow.com/questions/27848934/download-image-from-skipper-gridfs-in-sails-js

module.exports.custom = {
  fileUploads: { adapter: require('skipper-gridfs'), uri: 'mongodb://localhost:27017/payment_db', },
};

FileManagerController.js
...
      let blobAdapterOpts = _.omit(sails.config.custom.fileUploads, 'adapter');
      let configuredBlobAdapter = sails.config.custom.fileUploads.adapter(blobAdapterOpts);
      let fileStream = await configuredBlobAdapter.read(file.background.fd);
      fileStream.on('error', function (err){
        return res.serverError(err);
      });
      res.contentType(file.background.type);
      return fileStream.pipe(res);
...
```

**Comment by willhuang85** [comment]
not sure why there is an `await` as `read` returns a stream and not a promise.

But anyway, you can do something like this found in the skipper-adapter-tests:
https://github.com/balderdashy/skipper-adapter-https://github.com/balderdashy/skipper-adapter-tests/blob/master/tests/base/req.file.pipe.test.js#L59

**Comment by heoyongun** [comment]
> 가 왜 확실하지 `await`같은 `read`스트림이 아닌 약속을 반환합니다.
> 
> 그러나 어쨌든 skipper-adapter-tests에서 찾을 수있는 것과 같은 것을 할 수 있습니다 : 
> [https://github.com/balderdashy/skipper-adapter-tests/blob/master/tests/base/req.file.pipe.test. js # L59](https://github.com/balderdashy/skipper-adapter-tests/blob/master/tests/base/req.file.pipe.test.js#L59)

I changed the code.

Upload works well.
However, a download error occurs.
An error still occurs.

```
Sails v1.0.1
"skipper-gridfs": "^1.0.0",
```

```
  imageViewer: function (req, res) {

      var blobAdapter = require('skipper-gridfs')({
        uri: 'mongodb://localhost:27017/payment_db'
      });

      blobAdapter.read("2ede9121-1272-4abd-a9bf-e39668a336e1.xlsx", function(error , file) {
        if(error) {
            res.json(error);
        } else {
            res.contentType('image/jpeg');
            res.send(new Buffer(file));
        }
      });
  },
```

ERROR
```
Error: FileNotFound: file undefined was not found
download.js:277
    at /home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/gridfs-stream/download.js:277:17
    at result (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:414:17)
    at session.endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:401:11)
    at ClientSession.endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/sessions.js:129:41)
    at executeCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:397:17)
    at handleCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.next (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/operations/collection_ops.js:583:5)
    at result (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:128:55)
    at cursor._next (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/operations/cursor_ops.js:187:5)
    at handleCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:203:5)
    at _setCursorNotifiedImpl (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:561:38)
    at self._endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:569:46)
    at Cursor._endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:194:5)
    at Cursor._endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/cursor.js:226:59)
```

**Comment by willhuang85** [comment]
So for now, the read function does not take into account the callback function.  It just returns a stream.

So it would something like this be:
```
imageViewer: function (req, res) {

      var blobAdapter = require('skipper-gridfs')({
        uri: 'mongodb://localhost:27017/payment_db'
      });

      var readStream = blobAdapter.read("2ede9121-1272-4abd-a9bf-e39668a336e1.xlsx");
      readStream.on('error', function (err){
          return res.serverError(err);
      });

      return readStream.pipe(res);
  }
```

If you need the content-type of the file you are reading then you'll either need to access gridFS directly to get the meta data of the file or you'll have to store the file in memory using `readStream.on('data', fn)` to get all the data and then get the meta data from the blob.

**Comment by heoyongun** [comment]
> So for now, the read function does not take into account the callback function. It just returns a stream.
> 
> So it would something like this be:
> 
> ```
> imageViewer: function (req, res) {
> 
>       var blobAdapter = require('skipper-gridfs')({
>         uri: 'mongodb://localhost:27017/payment_db'
>       });
> 
>       var readStream = blobAdapter.read("2ede9121-1272-4abd-a9bf-e39668a336e1.xlsx");
>       readStream.on('error', function (err){
>           return res.serverError(err);
>       });
> 
>       return readStream.pipe(res);
>   }
> ```
> If you need the content-type of the file you are reading then you'll either need to access gridFS directly to get the meta data of the file or you'll have to store the file in memory using `readStream.on('data', fn)` to get all the data and then get the meta data from the blob.

Unfortunately your guide does not work for me.
//2ede9121-1272-4abd-a9bf-e39668a336e1.xlsx is fd
```
  background: function (req, res) {
      try {
        var blobAdapter = require('skipper-gridfs')({
          uri: 'mongodb://localhost:27017/payment_db'
        });
        var readStream = blobAdapter.read("2ede9121-1272-4abd-a9bf-e39668a336e1.xlsx");
        readStream.on('error', function (err){
            return res.serverError(err);
        });
        return readStream.pipe(res);
      } catch (error) {
        console.log(error);
        debugger;
      }
  },
```
ERRROR
```
Error: FileNotFound: file undefined was not found
download.js:277
    at /home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/gridfs-stream/download.js:277:17
    at result (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:414:17)
    at session.endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:401:11)
    at ClientSession.endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/sessions.js:129:41)
    at executeCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:397:17)
    at handleCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.next (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/operations/collection_ops.js:583:5)
    at result (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/utils.js:128:55)
    at cursor._next (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/operations/cursor_ops.js:187:5)
    at handleCallback (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:203:5)
    at _setCursorNotifiedImpl (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:561:38)
    at self._endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:569:46)
    at Cursor._endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb-core/lib/cursor.js:194:5)
    at Cursor._endSession (/home/yongun/demo/gosails/node_modules/skipper-gridfs/node_modules/mongodb/lib/cursor.js:226:59)

```

And the exception is not handled and the system dies.
I am using sails 1.0.X. Middleware settings in [http.js] Should I change it?
this is my http.js info

```
module.exports.http = {

  middleware: {

    // Logs each request to the console
    requestLogger: function (req, res, next) {
      console.log("Requested :: ", req.method, req.url);
      return next();
    },

    // passport 설정
    // passportInit: require('passport').initialize(),
    // passportSession: require('passport').session(),

    order: [
      'cookieParser',
      'session',
      'requestLogger',
      // 'passportInit',
      // 'passportSession',
      'bodyParser',
      'compress',
      'poweredBy',
      'router',
      'www',
      'favicon',
    ],

  },

};

```

**Comment by willhuang85** [comment]
I think your `fd` might be wrong. It should be a full file path. Do you have access to your mongo instance?  You can double check what is stored in there.

**Comment by heoyongun** [comment]
Mongog instance is accessible.

![2018-12-04 09-30-30](https://user-images.githubusercontent.com/6076067/49410310-80f5ed80-f7a7-11e8-9ca9-4ef5182b9985.png)

What is the **full file path**?

**Comment by heoyongun** [comment]
> I think your `fd` might be wrong. It should be a full file path. Do you have access to your mongo instance? You can double check what is stored in there.

Mongog instance is accessible.

![2018-12-04 09-30-30](https://user-images.githubusercontent.com/6076067/49410310-80f5ed80-f7a7-11e8-9ca9-4ef5182b9985.png)

What is the **full file path**?

**Comment by willhuang85** [comment]
Can you try this:

```
imageViewer: function (req, res) {
      try {
        var blobAdapter = require('skipper-gridfs')({
          uri: 'mongodb://localhost:27017/payment_db'
        });
        var readStream = blobAdapter.read({_id: "2ede9121-1272-4abd-a9bf-e39668a336e1.xlsx"});
        readStream.on('error', function (err){
            return res.serverError(err);
        });
        return readStream.pipe(res);
      } catch (error) {
        console.log(error);
        debugger;
      }
  },
```

**Comment by willhuang85** [comment]
I'll update the code for version 1.0.1 so you will just pass in the string
