### ISSUE TITLE
 Error: FileNotFound: file [here is filename] was not found

### ISSUE THREAD

**Issue by dehimer** [willhuang85/skipper-gridfs#37]
Get error which crash my server on read operation.
It is happen when you try read file which is not exist.

Here is part of code where it is happens:
```
read(req, res) {
    const filename = req.params.name;

    const fileAdapter = require('skipper-gridfs')({
      uri: sails.config.gridfs.uri,
    });

    fileAdapter.read(filename, (err, file) => {
      if (err) return res.negotiate(err);
...
```

Error stacktrace I get in terminal:
```
Error: FileNotFound: file hong-kong-city.jpg was not found
    at /Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/gridfs-stream/download.js:276:17
    at result (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:410:17)
    at session.endSession (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:398:11)
    at ClientSession.endSession (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/sessions.js:134:41)
    at executeCallback (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:395:17)
    at handleCallback (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.next (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/operations/collection_ops.js:598:5)
    at result (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:410:17)
    at executeCallback (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:402:9)
    at handleCallback (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:128:55)
    at cursor._next (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/operations/cursor_ops.js:195:5)
    at handleCallback (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:204:5)
    at _setCursorNotifiedImpl (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:426:38)
    at self._endSession (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:434:46)
    at Cursor._endSession (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:195:5)
    at Cursor._endSession (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/cursor.js:231:59)
    at _setCursorNotifiedImpl (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:434:17)
    at setCursorNotified (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:426:3)
    at done (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:650:16)
    at queryCallback (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/cursor.js:701:18)
    at /Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at __handleError (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/gridfs-stream/download.js:413:9)
    at /Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/gridfs-stream/download.js:278:14
    at result (/Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb/lib/utils.js:410:17)
    [... lines matching original stack trace ...]
    at /Users/dehimer/Projects/tempust/tempust-server/node_modules/mongodb-core/lib/connection/pool.js:397:18
```

Made fix in my own branch. Will share soon.

**Comment by dehimer** [comment]
My fix in fork: https://github.com/dehimer/skipper-gridfs/blob/master/index.js

**Comment by dehimer** [comment]
Thank you for merge.
